language: node_js
dist: trusty
os:
  - linux
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - 'iojs'
  - '0.12'
  - '0.11'
  - '0.10'
before_install:
  - sudo apt-get install -y libnotify-bin
jobs:
  include:
    - stage: test
      script: npm test
